### PR TITLE
don't treat DenseResourceElementsAttr as dense ONNXConstant

### LINKED ISSUE #2344: Datatype not correctly parsed for Const-prop pass
When compiling a customer model, we see the following errors:

```
root@7bc1ee526dda:~/onnx-mlir/build# onnx-mlir --O3 --EmitLib --maccel=NNPA model.onnx --onnx-op-stats TXT -v
The ONNX model has 25071 elements in its initializers. This value would be close to and greater than the number of parameters in the model. Because there is no way to exactly count the number of parameters, this value can be used to have a rough idea of the number of parameters in the model.
loc("StatefulPartitionedCall/sequential/dense/MatMul"): error: reduction dimension must be the same
loc("StatefulPartitionedCall/sequential/dense/MatMul"): error: Failed to scan parameters successfully
loc("StatefulPartitionedCall/sequential/dense/MatMul"): error: 'onnx.MatMul' op shape inference failed
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Gemm 2nd dim of A is different than 1st dim of B
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Failed to scan parameters successfully
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: 'onnx.Gemm' op shape inference failed
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Gemm 2nd dim of A is different than 1st dim of B
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Failed to scan parameters successfully
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: 'onnx.Gemm' op shape inference failed
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Gemm 2nd dim of A is different than 1st dim of B
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Failed to scan parameters successfully
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: 'onnx.Gemm' op shape inference failed
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Gemm 2nd dim of A is different than 1st dim of B
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Failed to scan parameters successfully
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: 'onnx.Gemm' op shape inference failed
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Gemm 2nd dim of A is different than 1st dim of B
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Failed to scan parameters successfully
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: 'onnx.Gemm' op shape inference failed
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Gemm 2nd dim of A is different than 1st dim of B
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Failed to scan parameters successfully
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: 'onnx.Gemm' op shape inference failed
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Gemm 2nd dim of A is different than 1st dim of B
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: Failed to scan parameters successfully
loc(fused["StatefulPartitionedCall/sequential/dense/BiasAdd", "StatefulPartitionedCall/sequential/dense/MatMul"]): error: 'onnx.Gemm' op shape inference failed
onnx-mlir: /workdir/onnx-mlir/src/Dialect/Mlir/IndexExprBuilder.cpp:84: void onnx_mlir::IndexExprBuilder::assertHasShapeAndRank(mlir::Value): Assertion `hasShapeAndRank(value) && "expected value with shape and rank"' failed.
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted
```

### PR DESCRIPTION
**Pull request by sorenlassen**
This should prevent any ONNXConstantOp with a DenseResourceElementsAttr value from getting into constant propagation (which doesn't support DenseResourceElementsAttr).

fixes #2344

### CODE REVIEW

File: src/Dialect/ONNX/ONNXOps/OpHelper.cpp [hunk 1]
```diff
@@ -539,6 +539,12 @@ bool isDenseONNXConstant(Value result) {
   if (!isa_and_nonnull<ElementsAttr>(constOp.getValueAttr()))
     return false;
 
+  // Except DenseResourceElementsAttr is too hard to work with, since it
+  // sometimes has a different shape and element type than constOp, plus
+  // DenseResourceElementsAttr has a limited API.
+  if (isa<DenseResourceElementsAttr>(constOp.getValueAttr()))
+    return false;
+
```
Comment (tungld) [inline src/Dialect/ONNX/ONNXOps/OpHelper.cpp:547]: You might need to edit Line 538 too that contains DenseResourceElementsAttr.

**Review by tungld — APPROVED** [review]
LGTM. Thanks!

File: src/Dialect/ONNX/ONNXOps/OpHelper.cpp (hunk 1 above)
Comment (sorenlassen) [reply src/Dialect/ONNX/ONNXOps/OpHelper.cpp:547]: what I tried to express with the comment is that it's a two step process: 1st in lines 537-540 we require that 'value' is an ElementsAttr (which could be a DenseResourceElementsAttr), 2nd in lines 542-546 we enforce the further requirement that 'value' is not a DenseResourceElementsAttr (because it can behave in strange ways)
