### PR TITLE
interpret empty tensors as absent Resize inputs

### LINKED ISSUE #2276: yolov4 failed
@sorenlassen it seems yolov4 has failed  since this PR:
Screenshot 2023-05-26 at 17 20 27

### PR DESCRIPTION
**Pull request by sorenlassen**
The yolo4 model uses a float tensor with shape [0] to represent that roi
or scales is absent in accordance with the Resize v11 spec. This violates
the spec from v13 onwards which says that empty string
inputs represents absent arguments in the protobuf model representation.
We work around this by interpreting a tensor with empty shape as an
alternative way to express that an input is absent.

Fixes #2276

### CODE REVIEW

File: src/Dialect/ONNX/Rewrite.cpp [hunk 1]
```diff
@@ -179,6 +179,45 @@ bool AreTheSameAxesConstant(int64_t rank, Value lhs, Value rhs) {
...
+// =============================================================================
+// Rewrite pattern for Resize (not handled in Rewrite.td).
+// =============================================================================
+
+// The yolo4 model uses a float tensor with shape [0] to represent that roi
+// or scales is absent (in violation of the spec which says that empty string
+// inputs represents absent arguments in the protobuf model representation).
+// We work around this by interpreting a tensor with empty shape as an
+// alternative way to express that an input is absent.
+class EmptyTensorInputsResizePattern : public OpRewritePattern<ONNXResizeOp> {
```
Comment (tungld) [inline src/Dialect/ONNX/Rewrite.cpp:191]: Could you please add lit tests for this rewriting? Thanks!

File: src/Dialect/ONNX/Rewrite.cpp [hunk 2]
```diff
@@ -179,6 +179,45 @@ bool AreTheSameAxesConstant(int64_t rank, Value lhs, Value rhs) {
...
 
+// =============================================================================
+// Rewrite pattern for Resize (not handled in Rewrite.td).
+// =============================================================================
+
+// The yolo4 model uses a float tensor with shape [0] to represent that roi
+// or scales is absent (in violation of the spec which says that empty string
+// inputs represents absent arguments in the protobuf model representation).
+// We work around this by interpreting a tensor with empty shape as an
+// alternative way to express that an input is absent.
```
Comment (tungld) [inline src/Dialect/ONNX/Rewrite.cpp:190]: Got it. Thanks for the investigation!

**Review by tungld — APPROVED** [review]
LGTM. Please wait for Tong's comment before merging as he has done many works on this op.

@chentong319 could you take a look at this patch? Thanks!

File: src/Dialect/ONNX/Rewrite.cpp (hunk 1 above)
Comment (sorenlassen) [reply src/Dialect/ONNX/Rewrite.cpp:191]: good suggestion

done

**Comment by chentong319** [comment]
> uses a float tensor with shape [0] to represent that roi or scales is absent

Is this a bug or just legacy representation?
If we are sure that such representation is illegal or deprecated, we may try to update the model instead of modifying the compiler.

**Comment by sorenlassen** [comment]
update: I wrapped the logic to mutate the Resize operands in rewriter.updateRootInPlace() because I think the rewriter is supposed to be informed about changes to the operation graph in that way

**Review by chentong319 — APPROVED** [review]
Thanks for digging out the details.
